apiVersion: apps/v1
kind: Deployment
metadata:
  name: legal-doc-backend
spec:
  template:
    spec:
      containers:
      - name: backend
        resources:
          requests:
            memory: "4Gi"
            cpu: "1000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
            
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: legal-doc-ui
spec:
  template:
    spec:
      containers:
      - name: ui
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"